server:
  port: ":8080"
  read_header_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s

db:
  username: "postgres"
  host: "test_task1-db-1"
  port: "5432"
  dbname: "onlineStore"
  sslmode: "disable"
